import routeData from "@/app/data/route-data.json";

export type Priority = "Verde" | "Amarelo" | "Vermelho";
export type TaskNature = "Emissão" | "Verificação" | "Execução" | "Lembrete";
export type ModuleId =
  | "dashboard"
  | "clientes"
  | "financeiro"
  | "cobrancas"
  | "tarefas"
  | "operacional"
  | "rotas"
  | "documentos"
  | "recados"
  | "relatorios"
  | "configuracoes";
export type PermissionAction =
  | "visualizar"
  | "criar"
  | "editar"
  | "excluir"
  | "aprovar"
  | "exportar"
  | "configurar";
export type ClosingFrequency =
  "daily" | "weekday" | "fortnightly" | "fixed_days" | "month_end_next_day";
export type DueMode =
  | "days_after"
  | "weekday_same_week"
  | "next_payment_day"
  | "fortnight_window"
  | "manual_table";

export type ClosingRule = {
  id: string;
  name: string;
  frequency: ClosingFrequency;
  weekdays: number[];
  daysOfMonth: number[];
  requiresOrderCheck: boolean;
  active: boolean;
};

export type DueRule = {
  id: string;
  name: string;
  mode: DueMode;
  days: number;
  weekday: number;
  paymentDays: number[];
  active: boolean;
  type?: string;
  adjustment?: string;
};

export type ColorRule = {
  id: string;
  name: string;
  color: string;
  maxOpenPending: number | null;
  allowSupply: boolean;
  collectionDelayDays: number;
  cancelAfterUnpaid: boolean;
  action: string;
  priority: number;
};

export type CustomerGroup = {
  id: string;
  name: string;
  payerName: string;
  units: string[];
  inheritRules: boolean;
  payerClientId?: string;
};

export type Client = {
  id: string;
  name: string;
  document: string;
  email: string;
  whatsapp: string;
  company: string;
  closing: string;
  closingRuleId: string;
  dueRule: string;
  dueRuleId: string;
  priority: Priority;
  colorRuleId: string;
  groupId: string;
  requiresOrderCheck: boolean;
  payment: string;
  sending: string;
  issuer: string;
  collectors: string[];
  billing: string;
  reminders: boolean;
  cancellationDays: number;
  active: boolean;
  tags: string[];
  notes: string;
  legalName?: string;
  stateRegistration?: string;
  cep?: string;
  address?: string;
  priceTable?: string;
  score?: number;
  requiresManifest?: boolean;
};

export type Emission = {
  id: string;
  clientId: string;
  scheduledDate: string;
  originalDate: string;
  company: string;
  category: string;
  priority: "Alta" | "Média" | "Baixa";
  responsible: string;
  status: "Pendente" | "Emitida" | "Sem pedido" | "Cancelada";
  invoiceNumbers: string[];
  dueDate: string;
  observation: string;
  amount: number;
  orderCheck: "Não necessário" | "A verificar" | "Tem pedido" | "Sem pedido";
  autoGenerated: boolean;
};

export type Collection = {
  id: string;
  clientId: string;
  invoice: string;
  dueDate: string;
  amount: number;
  priority: Priority;
  status:
    | "Pendente"
    | "Em andamento"
    | "Paga"
    | "Baixada"
    | "Reagendada"
    | "Cancelamento pendente"
    | "Cancelado"
    | "Arquivada";
  responsible: string;
  nextContact: string;
  availableFrom: string;
  policyId: string;
  attempts: number;
  proofName?: string;
  paidAt?: string;
  approvedBy?: string;
  cancellationDate?: string;
  cancellationReason?: string;
  history: { at: string; user: string; channel: string; summary: string }[];
};

export type Task = {
  id: string;
  title: string;
  category: string;
  nature: TaskNature;
  days: string[];
  responsible: string;
  time: string;
  priority: "Alta" | "Média" | "Baixa";
  notes: string;
  subitems: string[];
  completed: boolean;
};

export type RouteRecord = {
  id: string;
  base: string;
  source: string;
  driver: string;
  batch: string;
  time: string;
  client: string;
  french: string;
  milk: string;
  notes: string;
  rule: "fixo" | "programado" | "sob-demanda";
  registered: boolean;
  checked: boolean;
  routeName?: string;
  point?: string;
  address?: string;
  order?: number;
  shift?: string;
  trip?: string;
  competency?: string;
  deliveryDate?: string;
  registrationStatus?: string;
  conferenceStatus?: string;
  alert?: string;
  product?: string;
  quantity?: number;
};

export type RouteDriver = {
  id: string;
  name: string;
  shortName: string;
  status: string;
  phone: string;
  company: string;
  availability: string;
  shifts: string[];
  days: string[];
  linkedRoutes: string[];
  substituteId: string;
  notes: string;
};

export type RoutePlan = {
  id: string;
  name: string;
  code: string;
  status: string;
  type: string;
  days: string[];
  driverId: string;
  substituteId: string;
  shift: string;
  trips: string[];
  departure: string;
  departurePoint: string;
  returnTime: string;
  validityStart: string;
  validityEnd: string;
  permanent: boolean;
  notes: string;
};

export type RouteCompetency = {
  id: string;
  label: string;
  month: number;
  year: number;
  status: string;
  preparation: number;
  confirmations: number;
  registration: number;
  conference: number;
  correction: number;
  publication: number;
  version: number;
  official: boolean;
};

export type OperationalHoliday = {
  id: string;
  name: string;
  date: string;
  annual: boolean;
  type: string;
  locality: string;
  status: string;
  routeBase: string;
  operationalRule: string;
  notifications: number[];
  notes: string;
};

export type RouteDivergence = {
  id: string;
  routeId: string;
  client: string;
  date: string;
  type: string;
  expected: string;
  found: string;
  description: string;
  responsible: string;
  priority: string;
  status: string;
};

export type RouteVersion = {
  id: string;
  competencyId: string;
  version: number;
  createdAt: string;
  createdBy: string;
  official: boolean;
  summary: string;
};

export type GeneratedDocument = {
  id: string;
  type: string;
  company: string;
  client: string;
  date: string;
  total: number;
  status: string;
};

export type Notice = {
  id: string;
  text: string;
  sender: string;
  recipients: string[];
  priority: "Alta" | "Média" | "Baixa";
  status: "Pendente" | "Em andamento" | "Concluído" | "Arquivado";
  clientId?: string;
  createdAt: string;
  createTask: boolean;
};

export type UserAccount = {
  id: string;
  name: string;
  email: string;
  role: string;
  profileId: string;
  active: boolean;
  companies: string[];
  username?: string;
  localPassword?: string;
};

export type PermissionProfile = {
  id: string;
  name: string;
  description: string;
  permissions: string[];
  moduleAccess: Partial<Record<ModuleId, PermissionAction[]>>;
};

export type ModuleDefinition = {
  id: ModuleId;
  name: string;
  description: string;
  enabled: boolean;
  tabs: string[];
};

export type AppearanceSettings = {
  appName: string;
  sidebarTitle: string;
  tagline: string;
  primary: string;
  secondary: string;
  background: string;
  surface: string;
  text: string;
  radius: number;
  density: "Compacta" | "Confortável";
  logo: string;
  loginBackground: string;
  thumbnail: string;
  favicon: string;
  darkPrimary: string;
  darkSecondary: string;
  darkBackground: string;
  darkSurface: string;
  darkText: string;
};

export type DocumentTemplate = {
  id: "Cotação" | "Comprovante de Entrega" | "Declaração Bancária";
  name: string;
  title: string;
  introduction: string;
  notes: string;
  active: boolean;
};

export type Settings = {
  companies: {
    name: string;
    document: string;
    email: string;
    phone: string;
    address: string;
    primary: string;
    logo: string;
    signature: string;
    stamp: string;
    bankName: string;
    agency: string;
    account: string;
    beneficiary: string;
  }[];
  users: UserAccount[];
  profiles: PermissionProfile[];
  modules: ModuleDefinition[];
  appearance: AppearanceSettings;
  documentTemplates: DocumentTemplate[];
  paymentMethods: string[];
  sendingMethods: string[];
  closingTypes: string[];
  closingRules: ClosingRule[];
  dueRules: DueRule[];
  colorRules: ColorRule[];
  customerGroups: CustomerGroup[];
  holidays: { date: string; name: string; type: string; driverRule: string }[];
  customFields: {
    entity: string;
    label: string;
    type: string;
    required: boolean;
  }[];
  priceTables: string[];
  routeStatuses: string[];
  driverStatuses: string[];
  holidayTypes: string[];
  competencyStatuses: string[];
  routePreparationDays: number;
  allowSelfVerification: boolean;
};

export type AppState = {
  clients: Client[];
  emissions: Emission[];
  collections: Collection[];
  tasks: Task[];
  routes: RouteRecord[];
  routePlans: RoutePlan[];
  routeDrivers: RouteDriver[];
  routeCompetencies: RouteCompetency[];
  routeHolidays: OperationalHoliday[];
  routeDivergences: RouteDivergence[];
  routeVersions: RouteVersion[];
  documents: GeneratedDocument[];
  notices: Notice[];
  settings: Settings;
  audit: { at: string; user: string; action: string }[];
};

const today = new Date().toISOString().slice(0, 10);

export const seedState: AppState = {
  clients: [
    {
      id: "c1",
      name: "SESI SJC",
      document: "03.774.819/0001-02",
      email: "financeiro@sesisjc.local",
      whatsapp: "(12) 99999-1101",
      company: "Indústria de Pães Nova Esperança",
      closing: "Diário",
      closingRuleId: "closing-daily-check",
      dueRule: "15 dias + próximo dia 10, 20 ou 30",
      dueRuleId: "due-sesi",
      priority: "Amarelo",
      colorRuleId: "color-yellow",
      groupId: "",
      requiresOrderCheck: true,
      payment: "Boleto",
      sending: "WhatsApp",
      issuer: "Yerardo",
      collectors: ["Natanael", "Willians"],
      billing: "Nota Fiscal + Comprovante",
      reminders: true,
      cancellationDays: 5,
      active: true,
      tags: ["educação", "grande"],
      notes:
        "Verificar no sistema de pedidos antes da emissão. Se não houver pedido, marcar Sem pedido.",
      legalName: "Serviço Social da Indústria - SESI",
      stateRegistration: "Isento",
      cep: "12200-000",
      address: "São José dos Campos - SP",
      priceTable: "TABELA EMPRESAS (E)",
      score: 742,
      requiresManifest: true,
    },
    {
      id: "c2",
      name: "Hospital Regional",
      document: "12.345.678/0001-90",
      email: "contas@hospitalregional.local",
      whatsapp: "(12) 99999-2202",
      company: "Indústria de Pães Nova Esperança",
      closing: "Diário",
      closingRuleId: "closing-daily",
      dueRule: "30 dias",
      dueRuleId: "due-30",
      priority: "Vermelho",
      colorRuleId: "color-red",
      groupId: "",
      requiresOrderCheck: false,
      payment: "Transferência",
      sending: "E-mail",
      issuer: "Yerardo",
      collectors: ["Natanael"],
      billing: "Nota Fiscal",
      reminders: true,
      cancellationDays: 1,
      active: true,
      tags: ["hospital", "crítico"],
      notes:
        "Vermelho: cobrar no dia seguinte ao vencimento e encaminhar cancelamento se não pagar.",
    },
    {
      id: "c3",
      name: "Sodexo",
      document: "08.123.222/0001-10",
      email: "faturamento@sodexo.local",
      whatsapp: "(11) 99999-3303",
      company: "Excelência do Pão",
      closing: "Mensal",
      closingRuleId: "closing-month-end",
      dueRule: "Tabela mensal personalizada",
      dueRuleId: "due-table",
      priority: "Amarelo",
      colorRuleId: "color-yellow",
      groupId: "",
      requiresOrderCheck: false,
      payment: "Boleto",
      sending: "Portal",
      issuer: "Natanael",
      collectors: ["Natanael", "Jessica"],
      billing: "Nota Fiscal",
      reminders: false,
      cancellationDays: 5,
      active: true,
      tags: ["alimentação", "grupo"],
      notes: "Tabela de vencimento própria.",
    },
    {
      id: "c4",
      name: "Johnson",
      document: "61.074.175/0001-38",
      email: "suprimentos@johnson.local",
      whatsapp: "(12) 99999-4404",
      company: "Excelência do Pão",
      closing: "Toda quarta-feira - congelados",
      closingRuleId: "closing-wednesday",
      dueRule: "28 dias",
      dueRuleId: "due-28",
      priority: "Verde",
      colorRuleId: "color-green",
      groupId: "",
      requiresOrderCheck: false,
      payment: "Depósito",
      sending: "E-mail",
      issuer: "Willians",
      collectors: ["Natanael"],
      billing: "Nota Fiscal + Comprovante",
      reminders: true,
      cancellationDays: 7,
      active: true,
      tags: ["indústria", "johnson"],
      notes: "Separar pães, lanches, extras e congelados.",
    },
    {
      id: "c5",
      name: "Santa Casa SJC",
      document: "45.186.053/0001-87",
      email: "fiscal@santacasasjc.local",
      whatsapp: "(12) 99999-5505",
      company: "Indústria de Pães Nova Esperança",
      closing: "Diário",
      closingRuleId: "closing-daily",
      dueRule: "30 dias",
      dueRuleId: "due-30",
      priority: "Verde",
      colorRuleId: "color-green",
      groupId: "",
      requiresOrderCheck: false,
      payment: "Boleto",
      sending: "E-mail",
      issuer: "Willians",
      collectors: ["Natanael"],
      billing: "Nota Fiscal",
      reminders: true,
      cancellationDays: 5,
      active: true,
      tags: ["hospital"],
      notes: "Emissões de domingo e segunda preparadas no domingo.",
    },
    {
      id: "c6",
      name: "Fadel Transportes",
      document: "07.260.364/0002-30",
      email: "compras@fadel.local",
      whatsapp: "(12) 99999-6606",
      company: "Excelência do Pão",
      closing: "Dia 25",
      closingRuleId: "closing-day-25",
      dueRule: "30 dias",
      dueRuleId: "due-30",
      priority: "Verde",
      colorRuleId: "color-green",
      groupId: "",
      requiresOrderCheck: false,
      payment: "Pix",
      sending: "E-mail",
      issuer: "Natanael",
      collectors: ["Natanael"],
      billing: "Nota Fiscal",
      reminders: true,
      cancellationDays: 5,
      active: true,
      tags: ["logística"],
      notes: "Cliente usado no modelo atual de cotação.",
    },
  ],
  emissions: [
    {
      id: "e1",
      clientId: "c1",
      scheduledDate: today,
      originalDate: today,
      company: "Indústria de Pães Nova Esperança",
      category: "Diário",
      priority: "Alta",
      responsible: "Yerardo",
      status: "Pendente",
      invoiceNumbers: [],
      dueDate: today,
      observation: "Verificar no sistema se existe pedido.",
      amount: 4850,
      orderCheck: "A verificar",
      autoGenerated: true,
    },
    {
      id: "e2",
      clientId: "c2",
      scheduledDate: today,
      originalDate: today,
      company: "Indústria de Pães Nova Esperança",
      category: "Diário",
      priority: "Alta",
      responsible: "Yerardo",
      status: "Pendente",
      invoiceNumbers: [],
      dueDate: today,
      observation: "",
      amount: 5432.1,
      orderCheck: "Não necessário",
      autoGenerated: true,
    },
  ],
  collections: [
    {
      id: "b1",
      clientId: "c2",
      invoice: "38190",
      dueDate: today,
      amount: 5432.1,
      priority: "Vermelho",
      policyId: "color-red",
      status: "Pendente",
      responsible: "Natanael",
      nextContact: today + "T08:00",
      availableFrom: today,
      attempts: 0,
      history: [],
    },
    {
      id: "b2",
      clientId: "c1",
      invoice: "38177",
      dueDate: today,
      amount: 4850,
      priority: "Amarelo",
      policyId: "color-yellow",
      status: "Pendente",
      responsible: "Natanael",
      nextContact: today + "T14:00",
      availableFrom: today,
      attempts: 0,
      history: [],
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "Emitir notas JOHNSON",
      category: "Notas Fiscais",
      nature: "Emissão",
      days: ["Quinta", "Domingo"],
      responsible: "Willians",
      time: "07:00",
      priority: "Alta",
      notes: "Separar Johnson, extras, lanches, congelados e pães franceses.",
      subitems: [
        "Johnson",
        "Johnson extras",
        "Johnson congelados",
        "Johnson pães com margarina",
        "Johnson lanches",
        "Johnson pão francês",
      ],
      completed: false,
    },
    {
      id: "t2",
      title: "Verificar notas SESI",
      category: "Notas Fiscais",
      nature: "Verificação",
      days: ["Quinta", "Domingo"],
      responsible: "Willians",
      time: "08:00",
      priority: "Alta",
      notes: "Verificar quais notas já foram emitidas por terceiros.",
      subitems: [
        "Jacareí",
        "SJC",
        "Caçapava",
        "Pinda",
        "Taubaté",
        "Cruzeiro",
        "Lorena",
        "Guarulhos",
      ],
      completed: false,
    },
    {
      id: "t3",
      title: "Emitir notas de quinta-feira",
      category: "Notas Fiscais",
      nature: "Emissão",
      days: ["Quinta"],
      responsible: "Willians",
      time: "08:30",
      priority: "Alta",
      notes: "Tarefas recorrentes exclusivas de quinta.",
      subitems: [
        "Toder",
        "Plastic",
        "Alojamento",
        "César",
        "Gerdau",
        "Brazul",
        "Iramec",
        "Santa Casa SJC",
        "Embraer / Gláucia / Marinela",
        "Etec",
      ],
      completed: false,
    },
    {
      id: "t4",
      title: "Produção de pão francês",
      category: "Produção",
      nature: "Execução",
      days: ["Quinta", "Sábado", "Domingo"],
      responsible: "Willians",
      time: "10:00",
      priority: "Média",
      notes: "No sábado produzir para domingo; no domingo, para segunda.",
      subitems: [
        "Francês",
        "Mini",
        "Baguete 70g",
        "Baguete 120g",
        "Baguete 400g",
        "Integral",
        "Mini integral",
      ],
      completed: false,
    },
    {
      id: "t5",
      title: "Produção de pão doce, bolos e confeitaria",
      category: "Produção",
      nature: "Execução",
      days: ["Quinta", "Domingo"],
      responsible: "Willians",
      time: "11:00",
      priority: "Média",
      notes: "Produção de domingo destinada à segunda-feira.",
      subitems: ["Pães doces", "Bolos", "Confeitaria"],
      completed: false,
    },
    {
      id: "t6",
      title: "Romaneios de entregas",
      category: "Romaneios",
      nature: "Lembrete",
      days: ["Quinta", "Domingo"],
      responsible: "Willians",
      time: "14:00",
      priority: "Alta",
      notes:
        "Emitir via sistema externo. No domingo preparar domingo e segunda.",
      subitems: ["Entregas de domingo", "Entregas de segunda"],
      completed: false,
    },
    {
      id: "t7",
      title: "Conferir etiquetas e folhas",
      category: "Etiquetas e Folhas",
      nature: "Verificação",
      days: ["Quinta", "Sábado", "Domingo"],
      responsible: "Willians",
      time: "15:00",
      priority: "Alta",
      notes: "Checklist antes da liberação.",
      subitems: [
        "Johnson pães com margarina",
        "Johnson lanches",
        "Igaratá",
        "Paraibuna + conferência motorista",
        "Folha de Santa Branca",
        "Folha de entregas das merendas de SJC",
        "Folha de entrega Merenda Tremembé",
        "Folha Jaguariúna",
        "Relatórios de merendas",
      ],
      completed: false,
    },
    {
      id: "t8",
      title: "Relatórios de produtos - líderes",
      category: "Relatórios",
      nature: "Execução",
      days: ["Sábado"],
      responsible: "Willians",
      time: "14:00",
      priority: "Média",
      notes: "Elaborar relatórios dos líderes para 14h e 21h, incluindo FDS.",
      subitems: ["Relatório 14h", "Relatório 21h", "Relatório FDS"],
      completed: false,
    },
    {
      id: "t9",
      title: "Relatórios de compras",
      category: "Relatórios",
      nature: "Execução",
      days: ["Quinta"],
      responsible: "Willians",
      time: "17:00",
      priority: "Média",
      notes: "Emitir relatórios nos dois horários.",
      subitems: ["Relatório 17h00", "Relatório 20h30"],
      completed: false,
    },
    {
      id: "t10",
      title: "Conferir pedidos com alteração",
      category: "Conferência",
      nature: "Verificação",
      days: ["Sábado", "Domingo"],
      responsible: "Willians",
      time: "16:00",
      priority: "Alta",
      notes: "Usar planilhas e conferir quadro de OK para cadastros.",
      subitems: [
        "Hospital São José",
        "Vivalle",
        "Pró Infância",
        "Santa Casa SJC",
        "Hospital Santos Dumont",
        "Francisca Júlia",
      ],
      completed: false,
    },
    {
      id: "t11",
      title: "Emitir notas de domingo e segunda",
      category: "Notas Fiscais",
      nature: "Emissão",
      days: ["Domingo"],
      responsible: "Willians",
      time: "06:30",
      priority: "Alta",
      notes:
        "As notas de segunda são preparadas no domingo com vencimento/competência de segunda.",
      subitems: [
        "Oxiteno",
        "Jarinu",
        "Santa Casa SJC - domingo",
        "Santa Casa SJC - segunda",
        "Vivalle - domingo",
        "Vivalle - segunda",
        "Johnson pães com margarina",
        "Johnson lanches",
        "Johnson pedidos extras",
        "Johnson congelados",
        "Johnson pães franceses",
      ],
      completed: false,
    },
  ],
  routes: routeData.records as RouteRecord[],
  routePlans: [
    {
      id: "route-norte",
      name: "Rota Norte",
      code: "RT-NOR-01",
      status: "Ativa",
      type: "Semana",
      days: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
      driverId: "driver-adeir",
      substituteId: "driver-valdir",
      shift: "Manhã",
      trips: ["1ª Viagem", "2ª Viagem"],
      departure: "05:30",
      departurePoint: "Panificadora",
      returnTime: "11:30",
      validityStart: "2026-09-01",
      validityEnd: "",
      permanent: true,
      notes: "Base oficial de dias úteis.",
    },
    {
      id: "route-centro",
      name: "Rota Centro",
      code: "RT-CEN-01",
      status: "Em revisão",
      type: "Semana",
      days: ["Segunda", "Quarta", "Sexta"],
      driverId: "driver-valdir",
      substituteId: "",
      shift: "Manhã",
      trips: ["1ª Viagem"],
      departure: "06:00",
      departurePoint: "Panificadora",
      returnTime: "10:30",
      validityStart: "2026-09-01",
      validityEnd: "",
      permanent: true,
      notes: "Revisar sequência antes da publicação.",
    },
    {
      id: "route-feriado",
      name: "Rota Feriado 07/09/2026",
      code: "RT-FER-0709",
      status: "Especial de feriado",
      type: "Feriado",
      days: ["Segunda"],
      driverId: "driver-adeir",
      substituteId: "",
      shift: "Manhã",
      trips: ["1ª Viagem"],
      departure: "06:30",
      departurePoint: "Panificadora",
      returnTime: "11:00",
      validityStart: "2026-09-07",
      validityEnd: "2026-09-07",
      permanent: false,
      notes: "Cópia independente baseada no domingo.",
    },
  ],
  routeDrivers: [
    {
      id: "driver-adeir",
      name: "Adeir dos Santos",
      shortName: "Adeir",
      status: "Ativo",
      phone: "(12) 99999-0101",
      company: "Nova Esperança",
      availability: "05:00 às 15:00",
      shifts: ["Manhã"],
      days: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
      linkedRoutes: ["route-norte", "route-feriado"],
      substituteId: "driver-valdir",
      notes: "Motorista padrão da Rota Norte.",
    },
    {
      id: "driver-valdir",
      name: "Valdir Pereira",
      shortName: "Valdir",
      status: "Ativo",
      phone: "(12) 99999-0202",
      company: "Nova Esperança",
      availability: "05:30 às 16:00",
      shifts: ["Manhã", "Tarde"],
      days: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Domingo"],
      linkedRoutes: ["route-centro"],
      substituteId: "",
      notes: "Substituto autorizado para a Rota Norte.",
    },
  ],
  routeCompetencies: [
    {
      id: "competency-2026-09",
      label: "Setembro/2026",
      month: 9,
      year: 2026,
      status: "Em cadastro",
      preparation: 100,
      confirmations: 92,
      registration: 82,
      conference: 76,
      correction: 67,
      publication: 40,
      version: 2,
      official: true,
    },
    {
      id: "competency-2026-08",
      label: "Agosto/2026",
      month: 8,
      year: 2026,
      status: "Arquivada",
      preparation: 100,
      confirmations: 100,
      registration: 100,
      conference: 100,
      correction: 100,
      publication: 100,
      version: 3,
      official: false,
    },
  ],
  routeHolidays: [
    {
      id: "holiday-0709",
      name: "Independência do Brasil",
      date: "2026-09-07",
      annual: true,
      type: "Nacional",
      locality: "Brasil",
      status: "Em preparação",
      routeBase: "Domingo",
      operationalRule: "Antecipar análise e confirmar clientes",
      notifications: [30, 15, 7, 3, 1],
      notes: "Quatro clientes aguardando confirmação.",
    },
  ],
  routeDivergences: [
    {
      id: "div-1",
      routeId: "route-norte",
      client: "Cliente ABC",
      date: "2026-09-01",
      type: "Quantidade",
      expected: "150 unidades",
      found: "120 unidades",
      description: "Faltam 30 unidades no sistema externo.",
      responsible: "Cadastro",
      priority: "Alta",
      status: "Aberta",
    },
  ],
  routeVersions: [
    {
      id: "version-sep-2",
      competencyId: "competency-2026-09",
      version: 2,
      createdAt: "2026-08-30T16:42:00.000Z",
      createdBy: "Administrador",
      official: true,
      summary: "Motoristas, horários e feriado 07/09 revisados.",
    },
    {
      id: "version-sep-1",
      competencyId: "competency-2026-09",
      version: 1,
      createdAt: "2026-08-28T14:20:00.000Z",
      createdBy: "Administrador",
      official: false,
      summary: "Versão inicial copiada de agosto.",
    },
  ],
  documents: [
    {
      id: "d1",
      type: "Cotação",
      company: "Indústria de Pães Nova Esperança",
      client: "SESI Taubaté",
      date: "2026-07-29",
      total: 256,
      status: "Finalizado",
    },
    {
      id: "d2",
      type: "Cotação",
      company: "Excelência do Pão",
      client: "Fadel Transportes",
      date: "2025-02-28",
      total: 285,
      status: "Finalizado",
    },
    {
      id: "d3",
      type: "Comprovante de Entrega",
      company: "Indústria de Pães Nova Esperança",
      client: "São José dos Campos",
      date: "2026-08-27",
      total: 0,
      status: "Gerado",
    },
  ],
  notices: [
    {
      id: "n1",
      text: "Cliente Sodexo solicitou renegociação. Aguardar análise da diretoria.",
      sender: "Natanael",
      recipients: ["Jessica", "Marcelo"],
      priority: "Alta",
      status: "Pendente",
      clientId: "c3",
      createdAt: "2026-08-26T08:30",
      createTask: false,
    },
    {
      id: "n2",
      text: "Conferir alterações do Hospital São José antes de cadastrar o fim de semana.",
      sender: "Jessica",
      recipients: ["Willians"],
      priority: "Alta",
      status: "Em andamento",
      clientId: "c5",
      createdAt: "2026-08-25T17:10",
      createTask: true,
    },
  ],
  settings: {
    companies: [
      {
        name: "Indústria de Pães Nova Esperança",
        document: "73.066.045/0001-32",
        email: "contato@paesnovaesperanca.com.br",
        phone: "(12) 3903-6462",
        address:
          "Avenida Dois, 181, Eldorado, São José dos Campos - SP, 12238-580",
        primary: "#c96520",
        logo: "/brand/nova-esperanca.jpg",
        signature: "/brand/assinatura-yerardo.png",
        stamp: "/brand/carimbo-nova-esperanca.png",
        bankName: "Banco Bradesco",
        agency: "0225",
        account: "27240-0",
        beneficiary: "Pereira Martins Panificadora Industrial LTDA",
      },
      {
        name: "Excelência do Pão",
        document: "07.260.364/0001-50",
        email: "excelenciadopao@hotmail.com",
        phone: "(12) 3204-7902",
        address:
          "Avenida Leonor de Almeida Ribeiro Souto, 227, Residencial União, São José dos Campos - SP",
        primary: "#b6862e",
        logo: "/brand/excelencia-do-pao.png",
        signature: "/brand/assinatura-excelencia.png",
        stamp: "",
        bankName: "Banco Bradesco",
        agency: "0225",
        account: "27240-0",
        beneficiary: "Excelência do Pão",
      },
    ],
    users: [
      {
        id: "u-admin",
        name: "Administrador",
        email: "admin@gestao.local",
        role: "Administrador",
        profileId: "profile-admin",
        active: true,
        companies: ["*"],
        username: "admin",
        localPassword: "Admin@123",
      },
      {
        id: "u-yerardo",
        name: "Yerardo",
        email: "yerardo@gestao.local",
        role: "Financeiro principal",
        profileId: "profile-financeiro",
        active: true,
        companies: ["*"],
        username: "yerardo",
        localPassword: "Acesso@123",
      },
      {
        id: "u-natanael",
        name: "Natanael",
        email: "natanael@gestao.local",
        role: "Cobranças",
        profileId: "profile-cobrancas",
        active: true,
        companies: ["*"],
        username: "natanael",
        localPassword: "Acesso@123",
      },
      {
        id: "u-willians",
        name: "Willians",
        email: "willians@gestao.local",
        role: "Operações",
        profileId: "profile-operacoes",
        active: true,
        companies: ["*"],
        username: "willians",
        localPassword: "Acesso@123",
      },
      {
        id: "u-jessica",
        name: "Jessica",
        email: "jessica@gestao.local",
        role: "Diretoria",
        profileId: "profile-diretoria",
        active: true,
        companies: ["*"],
        username: "jessica",
        localPassword: "Acesso@123",
      },
      {
        id: "u-marcelo",
        name: "Marcelo",
        email: "marcelo@gestao.local",
        role: "Diretoria",
        profileId: "profile-diretoria",
        active: true,
        companies: ["*"],
        username: "marcelo",
        localPassword: "Acesso@123",
      },
    ],
    profiles: [
      {
        id: "profile-admin",
        name: "Administrador",
        description:
          "Acesso total, inclusive criação de perfis e personalização.",
        permissions: ["todos"],
        moduleAccess: {
          dashboard: ["visualizar", "configurar"],
          clientes: ["visualizar", "criar", "editar", "excluir", "configurar"],
          financeiro: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "exportar",
            "configurar",
          ],
          cobrancas: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "exportar",
            "configurar",
          ],
          tarefas: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "configurar",
          ],
          operacional: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "exportar",
            "configurar",
          ],
          rotas: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "exportar",
            "configurar",
          ],
          documentos: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "exportar",
            "configurar",
          ],
          recados: ["visualizar", "criar", "editar", "excluir"],
          relatorios: ["visualizar", "exportar"],
          configuracoes: [
            "visualizar",
            "criar",
            "editar",
            "excluir",
            "aprovar",
            "configurar",
          ],
        },
      },
      {
        id: "profile-financeiro",
        name: "Financeiro principal",
        description: "Emissão de notas, agenda financeira e acompanhamento.",
        permissions: [
          "cliente:ler",
          "nota:criar",
          "nota:atualizar",
          "relatorio:ler",
        ],
        moduleAccess: {
          dashboard: ["visualizar"],
          clientes: ["visualizar", "editar"],
          financeiro: ["visualizar", "criar", "editar", "exportar"],
          cobrancas: ["visualizar"],
          documentos: ["visualizar", "criar", "exportar"],
          recados: ["visualizar", "criar"],
          relatorios: ["visualizar"],
        },
      },
      {
        id: "profile-cobrancas",
        name: "Cobranças",
        description:
          "Fila, calendário, contatos, comprovantes e reagendamentos.",
        permissions: [
          "cobranca:criar",
          "cobranca:atualizar",
          "pagamento:registrar",
          "relatorio:ler",
        ],
        moduleAccess: {
          dashboard: ["visualizar"],
          clientes: ["visualizar", "editar"],
          financeiro: ["visualizar"],
          cobrancas: ["visualizar", "criar", "editar"],
          recados: ["visualizar", "criar"],
          relatorios: ["visualizar"],
        },
      },
      {
        id: "profile-operacoes",
        name: "Operações",
        description:
          "Checklist, conferências, rotas, documentos e cancelamentos.",
        permissions: [
          "tarefa:atualizar",
          "rota:atualizar",
          "cancelamento:confirmar",
          "documento:criar",
        ],
        moduleAccess: {
          dashboard: ["visualizar"],
          clientes: ["visualizar"],
          cobrancas: ["visualizar", "editar"],
          tarefas: ["visualizar", "criar", "editar"],
          operacional: ["visualizar", "criar", "editar", "configurar"],
          rotas: ["visualizar", "criar", "editar", "aprovar"],
          documentos: ["visualizar", "criar", "exportar"],
          recados: ["visualizar", "criar"],
        },
      },
      {
        id: "profile-diretoria",
        name: "Diretoria",
        description:
          "Visão geral, baixa final, negociação e aprovação de cancelamentos.",
        permissions: [
          "todos:ler",
          "pagamento:baixar",
          "cancelamento:aprovar",
          "relatorio:ler",
        ],
        moduleAccess: {
          dashboard: ["visualizar"],
          clientes: ["visualizar"],
          financeiro: ["visualizar"],
          cobrancas: ["visualizar", "aprovar"],
          tarefas: ["visualizar"],
          operacional: ["visualizar"],
          rotas: ["visualizar"],
          documentos: ["visualizar"],
          recados: ["visualizar", "criar"],
          relatorios: ["visualizar", "exportar"],
        },
      },
    ],
    modules: [
      {
        id: "dashboard",
        name: "Visão geral",
        description: "Indicadores e prioridades de toda a operação.",
        enabled: true,
        tabs: ["Resumo", "Atividade"],
      },
      {
        id: "clientes",
        name: "Clientes",
        description: "Cadastro unificado, grupos, responsáveis e regras.",
        enabled: true,
        tabs: ["Lista", "Grupos", "Importação"],
      },
      {
        id: "financeiro",
        name: "Financeiro",
        description: "Agenda de fechamento, emissão e faturas.",
        enabled: true,
        tabs: [
          "Painel",
          "Calendário",
          "Contas a emitir",
          "Histórico",
          "Relatórios",
        ],
      },
      {
        id: "cobrancas",
        name: "Cobranças",
        description: "Fila, histórico, comprovantes, baixa e cancelamento.",
        enabled: true,
        tabs: ["Painel", "Calendário", "Fila", "Histórico", "Cancelamentos"],
      },
      {
        id: "tarefas",
        name: "Tarefas da equipe",
        description: "Tarefas por perfil, recorrências e planner da equipe.",
        enabled: true,
        tabs: ["Meu dia", "Planner", "Catálogo", "Recorrências", "Indicadores"],
      },
      {
        id: "operacional",
        name: "Operacional",
        description:
          "Calculadoras de produção e ferramentas práticas da operação.",
        enabled: true,
        tabs: [
          "Calculadora de produção",
          "Categorias",
          "Produtos",
          "Histórico",
        ],
      },
      {
        id: "rotas",
        name: "Planejamento de rotas",
        description:
          "Central mensal de rotas, motoristas, feriados, cadastro e conferência.",
        enabled: true,
        tabs: [
          "Visão Geral",
          "Planner",
          "Base Mensal",
          "Consulta para Cadastro",
          "Próximo Mês",
          "Rotas",
          "Mapa",
          "Clientes e Paradas",
          "Motoristas",
          "Regras",
          "Feriados",
          "Conferência",
          "Pendências",
          "Histórico e Versões",
          "Indicadores",
          "Relatórios",
          "Configurações",
        ],
      },
      {
        id: "documentos",
        name: "Documentos",
        description: "Geradores, modelos e histórico corporativo.",
        enabled: true,
        tabs: ["Biblioteca", "Geradores", "Modelos", "Histórico"],
      },
      {
        id: "recados",
        name: "Recados",
        description: "Comunicação vinculada a clientes e fluxos.",
        enabled: true,
        tabs: ["Caixa de entrada", "Enviados"],
      },
      {
        id: "relatorios",
        name: "Relatórios",
        description: "Indicadores gerenciais dos módulos.",
        enabled: true,
        tabs: ["Financeiro", "Cobranças", "Tarefas", "Rotas"],
      },
      {
        id: "configuracoes",
        name: "Administração",
        description: "Usuários, perfis, módulos e personalização.",
        enabled: true,
        tabs: [
          "Identidade",
          "Usuários",
          "Perfis",
          "Módulos",
          "Campos",
          "Segurança",
        ],
      },
    ],
    appearance: {
      appName: "Gestão Operacional",
      sidebarTitle: "Gestão Operacional",
      tagline: "Um único lugar para organizar o que move a operação.",
      primary: "#c96520",
      secondary: "#17324d",
      background: "#f5f1ec",
      surface: "#ffffff",
      text: "#1d2835",
      radius: 14,
      density: "Confortável",
      logo: "/brand/nova-esperanca.jpg",
      loginBackground: "",
      thumbnail: "/brand/nova-esperanca.jpg",
      favicon: "/brand/nova-esperanca.jpg",
      darkPrimary: "#e98942",
      darkSecondary: "#8fb8da",
      darkBackground: "#0f1720",
      darkSurface: "#18232e",
      darkText: "#edf3f7",
    },
    documentTemplates: [
      {
        id: "Cotação",
        name: "Cotação / Proposta",
        title: "Proposta comercial",
        introduction:
          "apresenta sua proposta comercial para o fornecimento dos itens abaixo.",
        notes:
          "Os valores incluem custos operacionais, transporte e encargos incidentes no fornecimento. Validade: 90 dias. Pagamento: 30 dias.",
        active: true,
      },
      {
        id: "Comprovante de Entrega",
        name: "Comprovante de Entrega",
        title: "COMPROVANTE DE ENTREGA",
        introduction: "Relação dos itens entregues no local e data informados.",
        notes: "Recebimento sujeito à assinatura e conferência do responsável.",
        active: true,
      },
      {
        id: "Declaração Bancária",
        name: "Declaração de Dados Bancários",
        title: "DECLARAÇÃO DE DADOS BANCÁRIOS",
        introduction: "Declaramos os dados bancários para o crédito informado.",
        notes: "Documento emitido pela empresa selecionada.",
        active: true,
      },
    ],
    paymentMethods: [
      "Boleto",
      "Pix",
      "Depósito",
      "Transferência",
      "Dinheiro",
      "Cartão",
    ],
    sendingMethods: ["E-mail", "WhatsApp", "Mensagem", "Portal", "Outro"],
    closingTypes: [
      "Diário",
      "Toda segunda-feira",
      "Toda quarta-feira - congelados",
      "Toda sexta-feira",
      "Quinzenal",
      "Dia fixo",
      "Mensal - 1º dia do próximo mês",
    ],
    closingRules: [
      {
        id: "closing-daily",
        name: "Diário",
        frequency: "daily",
        weekdays: [],
        daysOfMonth: [],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-daily-check",
        name: "Diário - verificar pedido",
        frequency: "daily",
        weekdays: [],
        daysOfMonth: [],
        requiresOrderCheck: true,
        active: true,
      },
      {
        id: "closing-monday",
        name: "Toda segunda-feira",
        frequency: "weekday",
        weekdays: [1],
        daysOfMonth: [],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-wednesday",
        name: "Toda quarta-feira - congelados",
        frequency: "weekday",
        weekdays: [3],
        daysOfMonth: [],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-friday",
        name: "Toda sexta-feira",
        frequency: "weekday",
        weekdays: [5],
        daysOfMonth: [],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-fortnight",
        name: "Quinzenal - dia 15 e último dia",
        frequency: "fortnightly",
        weekdays: [],
        daysOfMonth: [15],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-day-20",
        name: "Dia 20",
        frequency: "fixed_days",
        weekdays: [],
        daysOfMonth: [20],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-day-25",
        name: "Dia 25",
        frequency: "fixed_days",
        weekdays: [],
        daysOfMonth: [25],
        requiresOrderCheck: false,
        active: true,
      },
      {
        id: "closing-month-end",
        name: "Mensal - emitir no 1º dia do próximo mês",
        frequency: "month_end_next_day",
        weekdays: [],
        daysOfMonth: [],
        requiresOrderCheck: false,
        active: true,
      },
    ],
    dueRules: [
      {
        id: "due-15",
        name: "15 dias",
        mode: "days_after",
        days: 15,
        weekday: 0,
        paymentDays: [],
        active: true,
      },
      {
        id: "due-28",
        name: "28 dias",
        mode: "days_after",
        days: 28,
        weekday: 0,
        paymentDays: [],
        active: true,
      },
      {
        id: "due-30",
        name: "30 dias",
        mode: "days_after",
        days: 30,
        weekday: 0,
        paymentDays: [],
        active: true,
      },
      {
        id: "due-same-wednesday",
        name: "Quarta-feira da mesma semana",
        mode: "weekday_same_week",
        days: 0,
        weekday: 3,
        paymentDays: [],
        active: true,
      },
      {
        id: "due-sesi",
        name: "15 dias + próximo dia 10, 20 ou 30",
        mode: "next_payment_day",
        days: 15,
        weekday: 0,
        paymentDays: [10, 20, 30],
        active: true,
      },
      {
        id: "due-fortnight",
        name: "Fechamento 1-15 vence dia 30; 16-fim vence dia 15",
        mode: "fortnight_window",
        days: 0,
        weekday: 0,
        paymentDays: [15, 30],
        active: true,
      },
      {
        id: "due-table",
        name: "Tabela mensal personalizada",
        mode: "manual_table",
        days: 0,
        weekday: 0,
        paymentDays: [],
        active: true,
      },
    ],
    colorRules: [
      {
        id: "color-red",
        name: "Vermelho",
        color: "#dc2626",
        maxOpenPending: 0,
        allowSupply: false,
        collectionDelayDays: 1,
        cancelAfterUnpaid: true,
        action:
          "Nenhuma pendência vencida permitida. Cobrar imediatamente no dia seguinte; sem pagamento, encaminhar cancelamento.",
        priority: 1,
      },
      {
        id: "color-yellow",
        name: "Amarelo",
        color: "#d97706",
        maxOpenPending: 2,
        allowSupply: true,
        collectionDelayDays: 1,
        cancelAfterUnpaid: true,
        action:
          "Até duas pendências vencidas em aberto; cobrança no dia seguinte e atenção ao limite.",
        priority: 2,
      },
      {
        id: "color-green",
        name: "Verde",
        color: "#15803d",
        maxOpenPending: null,
        allowSupply: true,
        collectionDelayDays: 1,
        cancelAfterUnpaid: false,
        action:
          "Pode ter várias pendências. Cobrança normal, sem cancelamento automático das entregas.",
        priority: 3,
      },
    ],
    customerGroups: [
      {
        id: "group-sr-mignon",
        name: "SR. Mignon",
        payerName: "SR. Mignon",
        inheritRules: true,
        units: [
          "Sr. Mignon Sede Nova",
          "Sr. Mignon Astronautas",
          "Prolind",
          "BCA",
          "Sr. Mignon Chácaras",
          "Safran",
          "Fantástico",
          "Globo Jambeiro",
          "Adatex Filial",
          "Adatex Matriz",
          "Vetcia",
          "Sany",
          "Cherry",
          "NHJ",
          "Premovale",
          "Legado Usimagem",
          "Armavale",
          "Larissa",
          "Rochinha",
          "Magnaghi",
        ],
      },
    ],
    holidays: [
      {
        date: "2026-09-07",
        name: "Independência do Brasil",
        type: "Nacional",
        driverRule: "Base de domingo",
      },
      {
        date: "2026-11-19",
        name: "Aniversário de São José dos Campos",
        type: "Municipal",
        driverRule: "Antecipar publicação",
      },
    ],
    customFields: [
      { entity: "Cliente", label: "Setor", type: "Texto", required: false },
      { entity: "Rota", label: "Viagem", type: "Seleção", required: true },
    ],
    priceTables: [
      "TABELA EMPRESAS (E)",
      "TABELA HOSPITAIS (H)",
      "TABELA MERENDAS (M)",
    ],
    routeStatuses: [
      "Ativa",
      "Em revisão",
      "Temporária",
      "Suspensa",
      "Arquivada",
      "Especial de feriado",
    ],
    driverStatuses: [
      "Ativo",
      "Inativo",
      "Férias",
      "Afastado",
      "Indisponível",
      "Temporário",
      "Substituto",
    ],
    holidayTypes: ["Nacional", "Estadual", "Regional", "Municipal"],
    competencyStatuses: [
      "Não iniciada",
      "Criada",
      "Em preparação",
      "Aguardando confirmação",
      "Em revisão",
      "Em cadastro",
      "Parcialmente cadastrada",
      "Cadastro concluído",
      "Em conferência",
      "Com divergências",
      "Corrigida",
      "Verificada",
      "Publicada",
      "Reaberta",
      "Finalizada",
      "Arquivada",
    ],
    routePreparationDays: 6,
    allowSelfVerification: false,
  },
  audit: [
    {
      at: "2026-08-26T09:15",
      user: "Natanael",
      action: "Registrou cobrança da NF 38190",
    },
    {
      at: "2026-08-26T08:30",
      user: "Sistema",
      action: "Gerou tarefas recorrentes de quarta-feira",
    },
    {
      at: "2026-08-25T18:02",
      user: "Willians",
      action: "Atualizou base de rotas do fim de semana",
    },
  ],
};

export const dayNames = [
  "Segunda",
  "Terça",
  "Quarta",
  "Quinta",
  "Sexta",
  "Sábado",
  "Domingo",
];
